### ISSUE TITLE
Switch to webpack for building

### ISSUE THREAD

**Issue by lukekarrys** [tweetyourbracket/tweetyourbracket.com#60]
- [x] Build with `NODE_ENV=production` to get dead code removal for prod builds

**Comment by rtorr** [comment]
:O I didnt know it did this.

**Comment by lukekarrys** [comment]
I've read that it does, but I need to verify. I also read that it also depends on the minifier.

**Comment by rtorr** [comment]
If it does do that, that is really cool.

**Comment by lukekarrys** [comment]
@rtorr The magic is right here: https://github.com/tweetyourbracket/tweetyourbracket.com/blob/master/webpack.config.js#L37-L42

Run it without `warnings: false` and it produces a ton of warnings about unreachable code. In the end my bundle size is about `17kb` smaller than with browserify (149kb -> 132kb min+gzip). I'm not sure if this is the full 17kb, but it probably helped. I think the webpack uglify plugin also has more aggressive options than I was using before
