### ISSUE TITLE
React 0.13 and react-router

### ISSUE THREAD

**Issue by lukekarrys** [tweetyourbracket/tweetyourbracket.com#78]
- [x] Dont use state mixin from router

**Comment by rtorr** [comment]
Ahhhh, im even falling behind on this. Still lurkin this.

**Comment by lukekarrys** [comment]
@rtorr Also it looks like mixins are only being deprecated in react-router and will still be supported in react, so I dont *have* to remove them, but I'd like to keep this project as idiomatic as possible. So I'm going to try and follow the new react-router docs from [this commit](https://github.com/rackt/react-router/commit/f3a44f1) and try and convert the components to es6 classes like in the [0.13 beta announcement](https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#mixins).

The main reason being I want to keep trying new stuff! :smile:

**Comment by lukekarrys** [comment]
Closed by a9ceb77
